### PR TITLE
Update node version

### PR DESCRIPTION
**Pull request by kumaraksh1**
NodeJs|16 actions are deprecated so need to move to latest NodeJs|20.

### CODE REVIEW

**Review by rmjoia — APPROVED** [review]

**Comment by Kahera** [comment]
any chance this could be merged and released soon?

**Comment by kumaraksh1** [comment]
@Kahera we are working on this.

**Review by Cyclosaryn — APPROVED** [review]
Exactly the line that needs to be fixed, nothing else! thank you!

**Comment by surenderssm** [comment]
This work is being tracked here : https://github.com/Azure/webapps-deploy/pull/407

**Pull request closed without merging**
